var data = [
  { nome: "BIOTECNOLOGIA", grau: "Bacharelado", turno: "Integral" },
  { nome: "CIÊNCIAS BIOLÓGICAS", grau: "Bacharelado", turno: "Integral" },
  {
    nome: "ABI - ARTES CÊNICAS",
    grau: "Área Básica de Ingresso (ABI)",
    turno: "Integral",
  },
  {
    nome: "ABI - CIÊNCIAS BIOLÓGICAS",
    grau: "Área Básica de Ingresso (ABI)",
    turno: "Integral",
  },
  { nome: "ADMINISTRAÇÃO", grau: "Bacharelado", turno: "Matutino" },
  { nome: "ADMINISTRAÇÃO", grau: "Bacharelado", turno: "Integral" },
  { nome: "AGRONEGÓCIO", grau: "Tecnológico", turno: "Matutino" },
  { nome: "ALIMENTOS", grau: "Tecnológico", turno: "Integral" },
  { nome: "ARQUITETURA E URBANISMO", grau: "Bacharelado", turno: "Integral" },
  { nome: "ARQUITETURA E URBANISMO", grau: "Bacharelado", turno: "Noturno" },
  { nome: "ARQUIVOLOGIA", grau: "Bacharelado", turno: "Integral" },
  { nome: "CIÊNCIAS ECONÔMICAS", grau: "Bacharelado", turno: "Integral" },
  {
    nome: "COMUNICAÇÃO SOCIAL - PRODUÇÃO EDITORIAL",
    grau: "Bacharelado",
    turno: "Integral",
  },
  {
    nome: "COMUNICAÇÃO SOCIAL - PUBLICIDADE E PROPAGANDA",
    grau: "Bacharelado",
    turno: "Integral",
  },
  {
    nome: "COMUNICAÇÃO SOCIAL - RELAÇÕES PÚBLICAS",
    grau: "Bacharelado",
    turno: "Integral",
  },
  { nome: "DESENHO INDUSTRIAL", grau: "Bacharelado", turno: "Integral" },
  { nome: "DIREITO", grau: "Bacharelado", turno: "Integral" },
  { nome: "EDUCAÇÃO ESPECIAL", grau: "Licenciatura", turno: "Integral" },
  { nome: "ELETRÔNICA INDUSTRIAL", grau: "Tecnológico", turno: "Integral" },
  { nome: "ENGENHARIA AEROESPACIAL", grau: "Bacharelado", turno: "Integral" },
  { nome: "ENGENHARIA AGRÍCOLA", grau: "Bacharelado", turno: "Integral" },
  {
    nome: "ENGENHARIA AMBIENTAL E SANITÁRIA",
    grau: "Bacharelado",
    turno: "Matutino",
  },
  {
    nome: "ENGENHARIA DE TELECOMUNICAÇÕES",
    grau: "Bacharelado",
    turno: "Integral",
  },
  {
    nome: "ENGENHARIA DE TRANSPORTES E LOGÍSTICA",
    grau: "Bacharelado",
    turno: "Noturno",
  },
  { nome: "ENGENHARIA FLORESTAL", grau: "Bacharelado", turno: "Integral" },
  { nome: "ESTATÍSTICA", grau: "Bacharelado", turno: "Noturno" },
  { nome: "FABRICAÇÃO MECÂNICA", grau: "Tecnológico", turno: "Integral" },
  { nome: "FILOSOFIA", grau: "Licenciatura", turno: "Integral" },
  { nome: "FONOAUDIOLOGIA", grau: "Bacharelado", turno: "Integral" },
  { nome: "GEOGRAFIA", grau: "Licenciatura", turno: "Integral" },
  { nome: "GEOGRAFIA", grau: "Bacharelado", turno: "Integral" },
  { nome: "GEOPROCESSAMENTO", grau: "Tecnológico", turno: "Integral" },
  { nome: "GESTÃO AMBIENTAL", grau: "Tecnológico", turno: "Integral" },
  { nome: "GESTÃO DE COOPERATIVAS", grau: "Tecnológico", turno: "Noturno" },
  { nome: "GESTÃO DE TURISMO", grau: "Tecnológico", turno: "Integral" },
  { nome: "HISTÓRIA", grau: "Licenciatura", turno: "Integral" },
  { nome: "HISTÓRIA", grau: "Bacharelado", turno: "Integral" },
  { nome: "JORNALISMO", grau: "Bacharelado", turno: "Integral" },
  { nome: "LETRAS - INGLÊS", grau: "Licenciatura", turno: "Integral" },
  {
    nome: "LETRAS - LÍNGUA PORTUGUESA",
    grau: "Bacharelado",
    turno: "Integral",
  },
  { nome: "LETRAS - PORTUGUÊS", grau: "Licenciatura", turno: "Integral" },
  { nome: "MATEMÁTICA", grau: "Bacharelado", turno: "Integral" },
  { nome: "ODONTOLOGIA", grau: "Bacharelado", turno: "Integral" },
  { nome: "PEDAGOGIA", grau: "Licenciatura", turno: "Integral" },
  { nome: "PROCESSOS QUÍMICOS", grau: "Tecnológico", turno: "Integral" },
  { nome: "QUÍMICA INDUSTRIAL", grau: "Bacharelado", turno: "Integral" },
  { nome: "REDES DE COMPUTADORES", grau: "Tecnológico", turno: "Integral" },
  { nome: "RELAÇÕES INTERNACIONAIS", grau: "Bacharelado", turno: "Integral" },
  { nome: "SISTEMAS DE INFORMAÇÃO", grau: "Bacharelado", turno: "Noturno" },
  { nome: "ARTES VISUAIS", grau: "Licenciatura", turno: "Matutino" },
  { nome: "ARTES VISUAIS", grau: "Licenciatura", turno: "Noturno" },
  { nome: "ARTES VISUAIS", grau: "Bacharelado", turno: "Vespertino" },
  { nome: "ARTES VISUAIS", grau: "Bacharelado", turno: "Noturno" },
  { nome: "CINEMA E AUDIOVISUAL", grau: "Bacharelado", turno: "Matutino" },
  { nome: "CIÊNCIAS CONTÁBEIS", grau: "Bacharelado", turno: "Matutino" },
  { nome: "LETRAS - ESPANHOL", grau: "Licenciatura", turno: "Noturno" },
  { nome: "LETRAS - INGLÊS", grau: "Licenciatura", turno: "Noturno" },
  { nome: "SECRETARIADO EXECUTIVO", grau: "Bacharelado", turno: "Noturno" },
  { nome: "TURISMO E NEGÓCIOS", grau: "Bacharelado", turno: "Noturno" },
  { nome: "MUSEOLOGIA", grau: "Bacharelado", turno: "Matutino" },
  { nome: "MÚSICA", grau: "Licenciatura", turno: "Vespertino" },
  { nome: "MUSICOTERAPIA", grau: "Bacharelado", turno: "Matutino" },
  { nome: "TEATRO", grau: "Licenciatura", turno: "Noturno" },
  { nome: "MECATRÔNICA INDUSTRIAL", grau: "Tecnológico", turno: "Matutino" },
  {
    nome: "ENGENHARIA AMBIENTAL E SANITÁRIA",
    grau: "Bacharelado",
    turno: "Integral",
  },
  { nome: "REDES DE COMPUTADORES", grau: "Tecnológico", turno: "Matutino" },
  { nome: "HOTELARIA", grau: "Tecnológico", turno: "Matutino" },
  {
    nome: "LETRAS - PORTUGUÊS E INGLÊS",
    grau: "Licenciatura",
    turno: "Integral",
  },
  {
    nome: "LETRAS - PORTUGUÊS E INGLÊS E RESPECTIVAS LITERATURAS",
    grau: "Licenciatura",
    turno: "Integral",
  },
  { nome: "IRRIGAÇÃO E DRENAGEM", grau: "Tecnológico", turno: "Integral" },
  { nome: "MECATRÔNICA INDUSTRIAL", grau: "Tecnológico", turno: "Integral" },
  { nome: "SANEAMENTO AMBIENTAL", grau: "Tecnológico", turno: "Integral" },
  { nome: "TEATRO", grau: "Licenciatura", turno: "Vespertino" },
  { nome: "ALIMENTOS", grau: "Tecnológico", turno: "Matutino" },
  { nome: "MÚSICA", grau: "Licenciatura", turno: "Noturno" },
  { nome: "NUTRIÇÃO", grau: "Bacharelado", turno: "Vespertino" },
  { nome: "SANEAMENTO AMBIENTAL", grau: "Tecnológico", turno: "Matutino" },
  { nome: "FÍSICA", grau: "Licenciatura", turno: "Matutino" },
  { nome: "GEOGRAFIA", grau: "Licenciatura", turno: "Matutino" },
  { nome: "MÚSICA", grau: "Licenciatura", turno: "Matutino" },
  { nome: "GESTÃO DE TURISMO", grau: "Tecnológico", turno: "Matutino" },
  { nome: "MATEMÁTICA", grau: "Licenciatura", turno: "Vespertino" },
  { nome: "ENGENHARIA AGRÍCOLA", grau: "Bacharelado", turno: "Matutino" },
  { nome: "ZOOTECNIA", grau: "Bacharelado", turno: "Matutino" },
  { nome: "AGROINDÚSTRIA", grau: "Tecnológico", turno: "Integral" },
  { nome: "GASTRONOMIA", grau: "Tecnológico", turno: "Integral" },
  { nome: "CIÊNCIAS BIOLÓGICAS", grau: "Licenciatura", turno: "Matutino" },
  { nome: "GESTÃO AMBIENTAL", grau: "Tecnológico", turno: "Matutino" },
  { nome: "CIÊNCIA DA COMPUTAÇÃO", grau: "Bacharelado", turno: "Noturno" },
  { nome: "ENGENHARIA DE AQUICULTURA", grau: "Bacharelado", turno: "Matutino" },
  { nome: "HOTELARIA", grau: "Tecnológico", turno: "Vespertino" },
  { nome: "SISTEMAS DE INFORMAÇÃO", grau: "Bacharelado", turno: "Matutino" },
  {
    nome: "ABI - EDUCAÇÃO FÍSICA",
    grau: "Área Básica de Ingresso (ABI)",
    turno: "Noturno",
  },
  {
    nome: "GESTÃO DA TECNOLOGIA DA INFORMAÇÃO",
    grau: "Tecnológico",
    turno: "Noturno",
  },
  { nome: "QUÍMICA", grau: "Licenciatura", turno: "Matutino" },
  { nome: "CIÊNCIAS NATURAIS", grau: "Licenciatura", turno: "Noturno" },
  { nome: "GESTÃO COMERCIAL", grau: "Tecnológico", turno: "Noturno" },
  { nome: "AGRONEGÓCIO", grau: "Tecnológico", turno: "Noturno" },
  { nome: "GESTÃO HOSPITALAR", grau: "Tecnológico", turno: "Vespertino" },
  { nome: "ENGENHARIA ELÉTRICA", grau: "Bacharelado", turno: "Noturno" },
];
